Add support for Swift 5.5 and async/await
brokenhandsio/leaf-error-middleware pull request #21
Opened 2021-12-02 15:48 UTC by ptoffy

Updated `swift-tools-version` to 5.5 and added `async/await` support to the project. 
Removed `EventLoopFuture` tests as they are redundant when using `async/await`.

2021-12-08 15:04 UTC, 0xTim commented
@ptoffy can you merge in the latest changes from `main` - that should trigger CI

2021-12-09 07:40 UTC, ptoffy commented
@0xTim I think the tests are failing because the installed version of swift on CI is 5.2

2021-12-09 14:18 UTC, 0xTim commented
@ptoffy yeah, now the CI is in your fork you should be able to change `swift:5.2-xenial` to `swift:5.5` etc

2021-12-18 11:30 UTC, ptoffy commented
@0xTim have you had any time to review this?

2021-12-20 15:12 UTC, 0xTim requested changes
This is great thanks! There's just a couple of missing tests and we're good to go!

2021-12-20 15:12 UTC, 0xTim commented on Tests/LeafErrorMiddlewareTests/DefaultLeafErrorMiddlewareTests.swift
> -    func testThatFuture403IsCaughtCorrectly() throws {
Could you add a test to ensure that 403s are caught? I'm sure they are but it was a previous issue so just want to make sure we don't add any regressions in the future!

2021-12-20 15:12 UTC, 0xTim commented on Tests/LeafErrorMiddlewareTests/DefaultLeafErrorMiddlewareTests.swift
> -            router.get("future403") { req -> EventLoopFuture<Response> in
As below, could you add a 403 test here? Thanks!

2021-12-20 15:12 UTC, 0xTim commented on Tests/LeafErrorMiddlewareTests/CustomGeneratorTests.swift
> -    func testThatFuture403IsCaughtCorrectly() throws {
I don't think we have a 403 test in this file, could you add one? Thanks!

2021-12-20 16:26 UTC, 0xTim approved these changes
Thanks!

2021-12-20 16:43 UTC, merged